/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(0.25 - exp2(-2.0)) < 0.001 ? 1 : -1] array0;
float[length(0.629960524947 - exp2(-0.666666666667)) < 0.001 ? 1 : -1] array1;
float[length(1.58740105197 - exp2(0.666666666667)) < 0.001 ? 1 : -1] array2;
float[length(4.0 - exp2(2.0)) < 0.001 ? 1 : -1] array3;

main()
{
  gl_FragColor = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length());
}
