/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[all(equal(bvec3(true, false, true), not(bvec3(false, true, false)))) ? 1 : -1] array0;

main()
{
  gl_Position  = vec4(array0.length());
}
