/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec3(0.2116, 0.2025, 1.0609) - matrixCompMult(mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5), mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec3(3.7636, 0.5625, 0.25) - matrixCompMult(mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5), mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec3(-0.6348, 0.5715, 1.03) - matrixCompMult(mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5), mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74))[0]) < 0.001 ? 1 : -1] array2;
float[length(vec3(-2.0952, -1.3725, 0.37) - matrixCompMult(mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5), mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74))[1]) < 0.001 ? 1 : -1] array3;
float[length(vec3(-0.6348, 0.5715, 1.03) - matrixCompMult(mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74), mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5))[0]) < 0.001 ? 1 : -1] array4;
float[length(vec3(-2.0952, -1.3725, 0.37) - matrixCompMult(mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74), mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5))[1]) < 0.001 ? 1 : -1] array5;
float[length(vec3(1.9044, 1.6129, 1.0) - matrixCompMult(mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74), mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74))[0]) < 0.001 ? 1 : -1] array6;
float[length(vec3(1.1664, 3.3489, 0.5476) - matrixCompMult(mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74), mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74))[1]) < 0.001 ? 1 : -1] array7;

main()
{
  gl_FragColor = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length()
                      + array4.length()
                      + array5.length()
                      + array6.length()
                      + array7.length());
}
