/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec2(3.2761, 1.3456) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec2(0.7569, 2.3104) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec2(0.6561, 0.0625) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[2]) < 0.001 ? 1 : -1] array2;
float[length(vec2(0.4225, 2.2801) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[3]) < 0.001 ? 1 : -1] array3;
float[length(vec2(3.4933, -0.5684) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[0]) < 0.001 ? 1 : -1] array4;
float[length(vec2(1.4181, -0.4104) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[1]) < 0.001 ? 1 : -1] array5;
float[length(vec2(0.2349, 0.035) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[2]) < 0.001 ? 1 : -1] array6;
float[length(vec2(1.04, -1.4194) - matrixCompMult(mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[3]) < 0.001 ? 1 : -1] array7;
float[length(vec2(3.4933, -0.5684) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[0]) < 0.001 ? 1 : -1] array8;
float[length(vec2(1.4181, -0.4104) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[1]) < 0.001 ? 1 : -1] array9;
float[length(vec2(0.2349, 0.035) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[2]) < 0.001 ? 1 : -1] array10;
float[length(vec2(1.04, -1.4194) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.81, -1.16, -0.87, -1.52, 0.81, 0.25, 0.65, -1.51))[3]) < 0.001 ? 1 : -1] array11;
float[length(vec2(3.7249, 0.2401) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[0]) < 0.001 ? 1 : -1] array12;
float[length(vec2(2.6569, 0.0729) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[1]) < 0.001 ? 1 : -1] array13;
float[length(vec2(0.0841, 0.0196) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[2]) < 0.001 ? 1 : -1] array14;
float[length(vec2(2.56, 0.8836) - matrixCompMult(mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94), mat4x2(1.93, 0.49, -1.63, 0.27, 0.29, 0.14, 1.6, 0.94))[3]) < 0.001 ? 1 : -1] array15;

main()
{
  gl_Position  = vec4(array0.length()
			    + array1.length()
			    + array2.length()
			    + array3.length()
			    + array4.length()
			    + array5.length()
			    + array6.length()
			    + array7.length()
			    + array8.length()
			    + array9.length()
			    + array10.length()
			    + array11.length()
			    + array12.length()
			    + array13.length()
			    + array14.length()
			    + array15.length());
}
