/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec3(0.0009, 0.0255, 0.0282) - outerProduct(vec3(-0.03, -0.85, -0.94), vec3(-0.03, -0.85, -0.94))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec3(0.0255, 0.7225, 0.799) - outerProduct(vec3(-0.03, -0.85, -0.94), vec3(-0.03, -0.85, -0.94))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec3(0.0282, 0.799, 0.8836) - outerProduct(vec3(-0.03, -0.85, -0.94), vec3(-0.03, -0.85, -0.94))[2]) < 0.001 ? 1 : -1] array2;
float[length(vec3(-0.0501, -1.4195, -1.5698) - outerProduct(vec3(-0.03, -0.85, -0.94), vec3(1.67, 0.66, 1.87))[0]) < 0.001 ? 1 : -1] array3;
float[length(vec3(-0.0198, -0.561, -0.6204) - outerProduct(vec3(-0.03, -0.85, -0.94), vec3(1.67, 0.66, 1.87))[1]) < 0.001 ? 1 : -1] array4;
float[length(vec3(-0.0561, -1.5895, -1.7578) - outerProduct(vec3(-0.03, -0.85, -0.94), vec3(1.67, 0.66, 1.87))[2]) < 0.001 ? 1 : -1] array5;
float[length(vec3(-0.0501, -0.0198, -0.0561) - outerProduct(vec3(1.67, 0.66, 1.87), vec3(-0.03, -0.85, -0.94))[0]) < 0.001 ? 1 : -1] array6;
float[length(vec3(-1.4195, -0.561, -1.5895) - outerProduct(vec3(1.67, 0.66, 1.87), vec3(-0.03, -0.85, -0.94))[1]) < 0.001 ? 1 : -1] array7;
float[length(vec3(-1.5698, -0.6204, -1.7578) - outerProduct(vec3(1.67, 0.66, 1.87), vec3(-0.03, -0.85, -0.94))[2]) < 0.001 ? 1 : -1] array8;
float[length(vec3(2.7889, 1.1022, 3.1229) - outerProduct(vec3(1.67, 0.66, 1.87), vec3(1.67, 0.66, 1.87))[0]) < 0.001 ? 1 : -1] array9;
float[length(vec3(1.1022, 0.4356, 1.2342) - outerProduct(vec3(1.67, 0.66, 1.87), vec3(1.67, 0.66, 1.87))[1]) < 0.001 ? 1 : -1] array10;
float[length(vec3(3.1229, 1.2342, 3.4969) - outerProduct(vec3(1.67, 0.66, 1.87), vec3(1.67, 0.66, 1.87))[2]) < 0.001 ? 1 : -1] array11;

main()
{
  gl_FragColor = vec4(array0.length()
			+ array1.length()
			+ array2.length()
			+ array3.length()
			+ array4.length()
			+ array5.length()
			+ array6.length()
			+ array7.length()
			+ array8.length()
			+ array9.length()
			+ array10.length()
			+ array11.length());
}
