/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec3(3.16227766017, 1.16774841624, 0.855398922768) - inversesqrt(vec3(0.1, 0.733333333333, 1.36666666667))) < 0.001 ? 1 : -1] array0;
float[length(vec3(0.707106781187, 3.16227766017, 1.16774841624) - inversesqrt(vec3(2.0, 0.1, 0.733333333333))) < 0.001 ? 1 : -1] array1;

main()
{
  gl_FragColor = vec4(array0.length()
			+ array1.length());
}
