/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec2(3.14159265359, 1.91063323625) - acos(vec2(-1.0, -0.333333333333))) < 0.001 ? 1 : -1] array0;
float[length(vec2(1.23095941734, 0.0) - acos(vec2(0.333333333333, 1.0))) < 0.001 ? 1 : -1] array1;

main()
{
  gl_FragColor = vec4(array0.length()
			+ array1.length());
}
