/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[equal(bvec3(false, false, true), bvec3(false, true, false))[0] ? 1 : -1] array0;
float[equal(bvec3(false, false, true), bvec3(false, true, false))[1] ? -1 : 1] array1;
float[equal(bvec3(false, false, true), bvec3(false, true, false))[2] ? -1 : 1] array2;
float[equal(bvec3(true, false, false), bvec3(true, false, true))[0] ? 1 : -1] array3;
float[equal(bvec3(true, false, false), bvec3(true, false, true))[1] ? 1 : -1] array4;
float[equal(bvec3(true, false, false), bvec3(true, false, true))[2] ? -1 : 1] array5;

main()
{
  gl_FragColor = vec4(array0.length()
			    + array1.length()
			    + array2.length()
			    + array3.length()
			    + array4.length()
			    + array5.length());
}
