/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec3(0.03, 0.85, 0.94) - reflect(vec3(-0.03, -0.85, -0.94), vec3(-0.02366537095, -0.670518843584, -0.741514956434))) < 0.001 ? 1 : -1] array0;
float[length(vec3(1.14715446187, -0.384777278543, 0.378131044128) - reflect(vec3(-0.03, -0.85, -0.94), vec3(0.644149390691, 0.254574010692, 0.721293030295))) < 0.001 ? 1 : -1] array1;
float[length(vec3(1.58155320473, -1.84599253267, -0.901332918482) - reflect(vec3(1.67, 0.66, 1.87), vec3(-0.02366537095, -0.670518843584, -0.741514956434))) < 0.001 ? 1 : -1] array2;
float[length(vec3(-1.67, -0.66, -1.87) - reflect(vec3(1.67, 0.66, 1.87), vec3(0.644149390691, 0.254574010692, 0.721293030295))) < 0.001 ? 1 : -1] array3;

main()
{
  gl_FragColor = vec4(array0.length()
			+ array1.length()
			+ array2.length()
			+ array3.length());
}
