/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec4(-1.65, 1.33, 1.93, 0.76)) < 2.96645106181 ? 1 : -1] array0;
float[2.96445106181 < length(vec4(-1.65, 1.33, 1.93, 0.76)) ? 1 : -1] array1;
float[length(vec4(0.8, -0.15, -0.51, 0.0)) < 0.961520692125 ? 1 : -1] array2;
float[0.959520692125 < length(vec4(0.8, -0.15, -0.51, 0.0)) ? 1 : -1] array3;

main()
{
  gl_Position  = vec4(array0.length()
			    + array1.length()
			    + array2.length()
			    + array3.length());
}
