/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec2(-0.46, 1.94) - transpose(mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec2(-0.45, -0.75) - transpose(mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec2(1.03, -0.5) - transpose(mat2x3(-0.46, -0.45, 1.03, 1.94, -0.75, -0.5))[2]) < 0.001 ? 1 : -1] array2;
float[length(vec2(1.38, -1.08) - transpose(mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74))[0]) < 0.001 ? 1 : -1] array3;
float[length(vec2(-1.27, 1.83) - transpose(mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74))[1]) < 0.001 ? 1 : -1] array4;
float[length(vec2(1.0, -0.74) - transpose(mat2x3(1.38, -1.27, 1.0, -1.08, 1.83, -0.74))[2]) < 0.001 ? 1 : -1] array5;

main()
{
  gl_Position  = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length()
                      + array4.length()
                      + array5.length());
}
