/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[all(equal(bvec4(true, false, true, false), not(bvec4(false, true, false, true)))) ? 1 : -1] array0;

main()
{
  gl_FragColor = vec4(array0.length());
}
