/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec4(3.16227766017, 1.16774841624, 0.855398922768, 0.707106781187) - inversesqrt(vec4(0.1, 0.733333333333, 1.36666666667, 2.0))) < 0.001 ? 1 : -1] array0;

main()
{
  gl_Position  = vec4(array0.length());
}
