/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec3(-0.03, -0.85, -0.94)) < 1.26867503722 ? 1 : -1] array0;
float[1.26667503722 < length(vec3(-0.03, -0.85, -0.94)) ? 1 : -1] array1;
float[length(vec3(1.67, 0.66, 1.87)) < 2.59356629616 ? 1 : -1] array2;
float[2.59156629616 < length(vec3(1.67, 0.66, 1.87)) ? 1 : -1] array3;

main()
{
  gl_FragColor = vec4(array0.length()
			    + array1.length()
			    + array2.length()
			    + array3.length());
}
