/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(-1.33) < 1.331 ? 1 : -1] array0;
float[1.329 < length(-1.33) ? 1 : -1] array1;
float[length(0.85) < 0.851 ? 1 : -1] array2;
float[0.849 < length(0.85) ? 1 : -1] array3;

main()
{
  gl_Position  = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length());
}
