/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec2(0.01, 0.12) - outerProduct(vec2(-0.1, -1.2), vec2(-0.1, -1.2))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec2(0.12, 1.44) - outerProduct(vec2(-0.1, -1.2), vec2(-0.1, -1.2))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec2(0.042, 0.504) - outerProduct(vec2(-0.1, -1.2), vec2(-0.42, 0.48))[0]) < 0.001 ? 1 : -1] array2;
float[length(vec2(-0.048, -0.576) - outerProduct(vec2(-0.1, -1.2), vec2(-0.42, 0.48))[1]) < 0.001 ? 1 : -1] array3;
float[length(vec2(0.042, -0.048) - outerProduct(vec2(-0.42, 0.48), vec2(-0.1, -1.2))[0]) < 0.001 ? 1 : -1] array4;
float[length(vec2(0.504, -0.576) - outerProduct(vec2(-0.42, 0.48), vec2(-0.1, -1.2))[1]) < 0.001 ? 1 : -1] array5;
float[length(vec2(0.1764, -0.2016) - outerProduct(vec2(-0.42, 0.48), vec2(-0.42, 0.48))[0]) < 0.001 ? 1 : -1] array6;
float[length(vec2(-0.2016, 0.2304) - outerProduct(vec2(-0.42, 0.48), vec2(-0.42, 0.48))[1]) < 0.001 ? 1 : -1] array7;

main()
{
  gl_FragColor = vec4(array0.length()
			+ array1.length()
			+ array2.length()
			+ array3.length()
			+ array4.length()
			+ array5.length()
			+ array6.length()
			+ array7.length());
}
