/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(0.0 - pow(0.0, 0.666666666667)) < 0.001 ? 1 : -1] array0;
float[length(0.0 - pow(0.0, 2.0)) < 0.001 ? 1 : -1] array1;
float[length(2.25 - pow(0.666666666667, -2.0)) < 0.001 ? 1 : -1] array2;
float[length(1.3103706971 - pow(0.666666666667, -0.666666666667)) < 0.001 ? 1 : -1] array3;
float[length(0.763142828369 - pow(0.666666666667, 0.666666666667)) < 0.001 ? 1 : -1] array4;
float[length(0.444444444444 - pow(0.666666666667, 2.0)) < 0.001 ? 1 : -1] array5;
float[length(0.5625 - pow(1.33333333333, -2.0)) < 0.001 ? 1 : -1] array6;
float[length(0.825481812224 - pow(1.33333333333, -0.666666666667)) < 0.001 ? 1 : -1] array7;
float[length(1.21141372855 - pow(1.33333333333, 0.666666666667)) < 0.001 ? 1 : -1] array8;
float[length(1.77777777778 - pow(1.33333333333, 2.0)) < 0.001 ? 1 : -1] array9;
float[length(0.25 - pow(2.0, -2.0)) < 0.001 ? 1 : -1] array10;
float[length(0.629960524947 - pow(2.0, -0.666666666667)) < 0.001 ? 1 : -1] array11;
float[length(1.58740105197 - pow(2.0, 0.666666666667)) < 0.001 ? 1 : -1] array12;
float[length(4.0 - pow(2.0, 2.0)) < 0.001 ? 1 : -1] array13;

main()
{
  gl_Position  = vec4(array0.length()
			    + array1.length()
			    + array2.length()
			    + array3.length()
			    + array4.length()
			    + array5.length()
			    + array6.length()
			    + array7.length()
			    + array8.length()
			    + array9.length()
			    + array10.length()
			    + array11.length()
			    + array12.length()
			    + array13.length());
}
