/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec4(1.65, -1.33, -1.93, -0.76) - reflect(vec4(-1.65, 1.33, 1.93, 0.76), vec4(-0.556407765836, 0.448498380947, 0.650828477615, 0.256284789113))) < 0.001 ? 1 : -1] array0;
float[length(vec4(2.69216345112, 0.515844352916, -0.838129200087, 0.76) - reflect(vec4(-1.65, 1.33, 1.93, 0.76), vec4(0.832881588662, -0.156165297874, -0.530962012772, 0.0))) < 0.001 ? 1 : -1] array1;
float[length(vec4(-0.139576297206, 0.607355439566, 0.589019547641, 0.432774536895) - reflect(vec4(0.8, -0.15, -0.51, 0.0), vec4(-0.556407765836, 0.448498380947, 0.650828477615, 0.256284789113))) < 0.001 ? 1 : -1] array2;
float[length(vec4(-0.8, 0.15, 0.51, 0.0) - reflect(vec4(0.8, -0.15, -0.51, 0.0), vec4(0.832881588662, -0.156165297874, -0.530962012772, 0.0))) < 0.001 ? 1 : -1] array3;

main()
{
  gl_Position  = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length());
}
