/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec3(0.003, 0.085, 0.094) - outerProduct(vec3(-0.03, -0.85, -0.94), vec2(-0.1, -1.2))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec3(0.036, 1.02, 1.128) - outerProduct(vec3(-0.03, -0.85, -0.94), vec2(-0.1, -1.2))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec3(0.0126, 0.357, 0.3948) - outerProduct(vec3(-0.03, -0.85, -0.94), vec2(-0.42, 0.48))[0]) < 0.001 ? 1 : -1] array2;
float[length(vec3(-0.0144, -0.408, -0.4512) - outerProduct(vec3(-0.03, -0.85, -0.94), vec2(-0.42, 0.48))[1]) < 0.001 ? 1 : -1] array3;
float[length(vec3(-0.167, -0.066, -0.187) - outerProduct(vec3(1.67, 0.66, 1.87), vec2(-0.1, -1.2))[0]) < 0.001 ? 1 : -1] array4;
float[length(vec3(-2.004, -0.792, -2.244) - outerProduct(vec3(1.67, 0.66, 1.87), vec2(-0.1, -1.2))[1]) < 0.001 ? 1 : -1] array5;
float[length(vec3(-0.7014, -0.2772, -0.7854) - outerProduct(vec3(1.67, 0.66, 1.87), vec2(-0.42, 0.48))[0]) < 0.001 ? 1 : -1] array6;
float[length(vec3(0.8016, 0.3168, 0.8976) - outerProduct(vec3(1.67, 0.66, 1.87), vec2(-0.42, 0.48))[1]) < 0.001 ? 1 : -1] array7;

main()
{
  gl_Position  = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length()
                      + array4.length()
                      + array5.length()
                      + array6.length()
                      + array7.length());
}
