/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[any(bvec3(false, false, false)) ? -1 : 1] array0;
float[any(bvec3(false, false, true)) ? 1 : -1] array1;
float[any(bvec3(false, true, false)) ? 1 : -1] array2;
float[any(bvec3(false, true, true)) ? 1 : -1] array3;
float[any(bvec3(true, false, false)) ? 1 : -1] array4;
float[any(bvec3(true, false, true)) ? 1 : -1] array5;
float[any(bvec3(true, true, false)) ? 1 : -1] array6;
float[any(bvec3(true, true, true)) ? 1 : -1] array7;

main()
{
  gl_FragColor = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length()
                      + array4.length()
                      + array5.length()
                      + array6.length()
                      + array7.length());
}
