/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec2(0.0081, 1.4161) - matrixCompMult(mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08), mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec2(1.69, 0.0064) - matrixCompMult(mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08), mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec2(1.5625, 1.1664) - matrixCompMult(mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08), mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08))[2]) < 0.001 ? 1 : -1] array2;
float[length(vec2(-0.0324, 0.6307) - matrixCompMult(mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08), mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79))[0]) < 0.001 ? 1 : -1] array3;
float[length(vec2(-1.404, 0.0704) - matrixCompMult(mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08), mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79))[1]) < 0.001 ? 1 : -1] array4;
float[length(vec2(-0.75, -1.9332) - matrixCompMult(mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08), mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79))[2]) < 0.001 ? 1 : -1] array5;
float[length(vec2(-0.0324, 0.6307) - matrixCompMult(mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79), mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08))[0]) < 0.001 ? 1 : -1] array6;
float[length(vec2(-1.404, 0.0704) - matrixCompMult(mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79), mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08))[1]) < 0.001 ? 1 : -1] array7;
float[length(vec2(-0.75, -1.9332) - matrixCompMult(mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79), mat3x2(0.09, -1.19, 1.3, 0.08, 1.25, 1.08))[2]) < 0.001 ? 1 : -1] array8;
float[length(vec2(0.1296, 0.2809) - matrixCompMult(mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79), mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79))[0]) < 0.001 ? 1 : -1] array9;
float[length(vec2(1.1664, 0.7744) - matrixCompMult(mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79), mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79))[1]) < 0.001 ? 1 : -1] array10;
float[length(vec2(0.36, 3.2041) - matrixCompMult(mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79), mat3x2(-0.36, -0.53, -1.08, 0.88, -0.6, -1.79))[2]) < 0.001 ? 1 : -1] array11;

main()
{
  gl_FragColor = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length()
                      + array4.length()
                      + array5.length()
                      + array6.length()
                      + array7.length()
                      + array8.length()
                      + array9.length()
                      + array10.length()
                      + array11.length());
}
