/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec2(0.16, -1.69) - transpose(mat2x4(0.16, -0.8, -1.74, -0.02, -1.69, 0.59, -1.43, -1.21))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec2(-0.8, 0.59) - transpose(mat2x4(0.16, -0.8, -1.74, -0.02, -1.69, 0.59, -1.43, -1.21))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec2(-1.74, -1.43) - transpose(mat2x4(0.16, -0.8, -1.74, -0.02, -1.69, 0.59, -1.43, -1.21))[2]) < 0.001 ? 1 : -1] array2;
float[length(vec2(-0.02, -1.21) - transpose(mat2x4(0.16, -0.8, -1.74, -0.02, -1.69, 0.59, -1.43, -1.21))[3]) < 0.001 ? 1 : -1] array3;
float[length(vec2(-1.02, 0.74) - transpose(mat2x4(-1.02, -1.64, -1.59, 0.3, 0.74, -0.13, 0.47, 1.13))[0]) < 0.001 ? 1 : -1] array4;
float[length(vec2(-1.64, -0.13) - transpose(mat2x4(-1.02, -1.64, -1.59, 0.3, 0.74, -0.13, 0.47, 1.13))[1]) < 0.001 ? 1 : -1] array5;
float[length(vec2(-1.59, 0.47) - transpose(mat2x4(-1.02, -1.64, -1.59, 0.3, 0.74, -0.13, 0.47, 1.13))[2]) < 0.001 ? 1 : -1] array6;
float[length(vec2(0.3, 1.13) - transpose(mat2x4(-1.02, -1.64, -1.59, 0.3, 0.74, -0.13, 0.47, 1.13))[3]) < 0.001 ? 1 : -1] array7;

main()
{
  gl_FragColor = vec4(array0.length()
			+ array1.length()
			+ array2.length()
			+ array3.length()
			+ array4.length()
			+ array5.length()
			+ array6.length()
			+ array7.length());
}
