/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec3(-1.11, 1.67, -0.41) - transpose(mat3(-1.11, 0.13, 0.56, 1.67, 1.09, 0.95, -0.41, -0.02, 0.24))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec3(0.13, 1.09, -0.02) - transpose(mat3(-1.11, 0.13, 0.56, 1.67, 1.09, 0.95, -0.41, -0.02, 0.24))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec3(0.56, 0.95, 0.24) - transpose(mat3(-1.11, 0.13, 0.56, 1.67, 1.09, 0.95, -0.41, -0.02, 0.24))[2]) < 0.001 ? 1 : -1] array2;
float[length(vec3(-1.69, -0.46, -0.18) - transpose(mat3(-1.69, -1.09, -1.53, -0.46, 1.75, -0.7, -0.18, 2.0, -1.47))[0]) < 0.001 ? 1 : -1] array3;
float[length(vec3(-1.09, 1.75, 2.0) - transpose(mat3(-1.69, -1.09, -1.53, -0.46, 1.75, -0.7, -0.18, 2.0, -1.47))[1]) < 0.001 ? 1 : -1] array4;
float[length(vec3(-1.53, -0.7, -1.47) - transpose(mat3(-1.69, -1.09, -1.53, -0.46, 1.75, -0.7, -0.18, 2.0, -1.47))[2]) < 0.001 ? 1 : -1] array5;

main()
{
  gl_Position  = vec4(array0.length()
			    + array1.length()
			    + array2.length()
			    + array3.length()
			    + array4.length()
			    + array5.length());
}
