/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[all(bvec2(false, false)) ? -1 : 1] array0;
float[all(bvec2(false, true)) ? -1 : 1] array1;
float[all(bvec2(true, false)) ? -1 : 1] array2;
float[all(bvec2(true, true)) ? 1 : -1] array3;

main()
{
  gl_Position  = vec4(array0.length()
                      + array1.length()
                      + array2.length()
                      + array3.length());
}
