/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec4(0.0, 0.816496580928, 1.15470053838, 1.41421356237) - sqrt(vec4(0.0, 0.666666666667, 1.33333333333, 2.0))) < 0.001 ? 1 : -1] array0;

main()
{
  gl_FragColor = vec4(array0.length());
}
