/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec4(-0.566666666667, -0.633333333333, -0.0333333333333, -0.1) - mod(vec4(-1.9, -0.633333333333, 0.633333333333, 1.9), -0.666666666667)) < 0.001 ? 1 : -1] array0;
float[length(vec4(-1.9, -0.633333333333, -1.36666666667, -0.1) - mod(vec4(-1.9, -0.633333333333, 0.633333333333, 1.9), -2.0)) < 0.001 ? 1 : -1] array1;
float[length(vec4(0.1, 0.0333333333333, 0.633333333333, 0.566666666667) - mod(vec4(-1.9, -0.633333333333, 0.633333333333, 1.9), 0.666666666667)) < 0.001 ? 1 : -1] array2;
float[length(vec4(0.1, 1.36666666667, 0.633333333333, 1.9) - mod(vec4(-1.9, -0.633333333333, 0.633333333333, 1.9), 2.0)) < 0.001 ? 1 : -1] array3;

main()
{
  gl_FragColor = vec4(array0.length()
			    + array1.length()
			    + array2.length()
			    + array3.length());
}
