/* [config]
 * expect_result: pass
 * glsl_version: 1.20
 * [end config]
 * Automatically generated by gen_constant_array_size_tests.py
 */
#version 120

float[length(vec2(0.165, 1.98) - outerProduct(vec2(-0.1, -1.2), vec4(-1.65, 1.33, 1.93, 0.76))[0]) < 0.001 ? 1 : -1] array0;
float[length(vec2(-0.133, -1.596) - outerProduct(vec2(-0.1, -1.2), vec4(-1.65, 1.33, 1.93, 0.76))[1]) < 0.001 ? 1 : -1] array1;
float[length(vec2(-0.193, -2.316) - outerProduct(vec2(-0.1, -1.2), vec4(-1.65, 1.33, 1.93, 0.76))[2]) < 0.001 ? 1 : -1] array2;
float[length(vec2(-0.076, -0.912) - outerProduct(vec2(-0.1, -1.2), vec4(-1.65, 1.33, 1.93, 0.76))[3]) < 0.001 ? 1 : -1] array3;
float[length(vec2(-0.08, -0.96) - outerProduct(vec2(-0.1, -1.2), vec4(0.8, -0.15, -0.51, 0.0))[0]) < 0.001 ? 1 : -1] array4;
float[length(vec2(0.015, 0.18) - outerProduct(vec2(-0.1, -1.2), vec4(0.8, -0.15, -0.51, 0.0))[1]) < 0.001 ? 1 : -1] array5;
float[length(vec2(0.051, 0.612) - outerProduct(vec2(-0.1, -1.2), vec4(0.8, -0.15, -0.51, 0.0))[2]) < 0.001 ? 1 : -1] array6;
float[length(vec2(-0, -0) - outerProduct(vec2(-0.1, -1.2), vec4(0.8, -0.15, -0.51, 0.0))[3]) < 0.001 ? 1 : -1] array7;
float[length(vec2(0.693, -0.792) - outerProduct(vec2(-0.42, 0.48), vec4(-1.65, 1.33, 1.93, 0.76))[0]) < 0.001 ? 1 : -1] array8;
float[length(vec2(-0.5586, 0.6384) - outerProduct(vec2(-0.42, 0.48), vec4(-1.65, 1.33, 1.93, 0.76))[1]) < 0.001 ? 1 : -1] array9;
float[length(vec2(-0.8106, 0.9264) - outerProduct(vec2(-0.42, 0.48), vec4(-1.65, 1.33, 1.93, 0.76))[2]) < 0.001 ? 1 : -1] array10;
float[length(vec2(-0.3192, 0.3648) - outerProduct(vec2(-0.42, 0.48), vec4(-1.65, 1.33, 1.93, 0.76))[3]) < 0.001 ? 1 : -1] array11;
float[length(vec2(-0.336, 0.384) - outerProduct(vec2(-0.42, 0.48), vec4(0.8, -0.15, -0.51, 0.0))[0]) < 0.001 ? 1 : -1] array12;
float[length(vec2(0.063, -0.072) - outerProduct(vec2(-0.42, 0.48), vec4(0.8, -0.15, -0.51, 0.0))[1]) < 0.001 ? 1 : -1] array13;
float[length(vec2(0.2142, -0.2448) - outerProduct(vec2(-0.42, 0.48), vec4(0.8, -0.15, -0.51, 0.0))[2]) < 0.001 ? 1 : -1] array14;
float[length(vec2(-0, 0.0) - outerProduct(vec2(-0.42, 0.48), vec4(0.8, -0.15, -0.51, 0.0))[3]) < 0.001 ? 1 : -1] array15;

main()
{
  gl_FragColor = vec4(array0.length()
			+ array1.length()
			+ array2.length()
			+ array3.length()
			+ array4.length()
			+ array5.length()
			+ array6.length()
			+ array7.length()
			+ array8.length()
			+ array9.length()
			+ array10.length()
			+ array11.length()
			+ array12.length()
			+ array13.length()
			+ array14.length()
			+ array15.length());
}
